### ISSUE TITLE
Getting error related to lcrt0.o library

### ISSUE THREAD

**Issue by piyushchauhan2011** [mity/cutest#4]
Hi @mity , I clone the repository and tried running `make` command on the examples folder you have provided. I got error regarding below:

```bash
gcc -I../include  -Wall -static c-example.c -o c-example
ld: library not found for -lcrt0.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [c-example] Error 1
```

Any help would be appreciated, my current xcode version:

```
xcode-select version 2343.
```

I already ran `xcode-select --install` but still getting the same error.

Thanking You!

**Comment by piyushchauhan2011** [comment]
Tried removing `-static` i.e. `${LDFLAGS}` and worked perfectly. Getting output like this, sweet 😄 
@mity 
![screen shot 2016-07-26 at 5 22 51 pm](https://cloud.githubusercontent.com/assets/693487/17129540/0f71c338-5357-11e6-9ca9-679fa30b34ff.png)

**Comment by mity** [comment]
Seems you are on Mac OS X, right? I don't have any mac around me right now. Could you try to remove `-static` and try again? If it helps, I'll cook some patch fixing it. I added that option mainly for Windows anyway, in order to not depend on `libgcc.dll`.

**Comment by piyushchauhan2011** [comment]
Haha Cool, worked!

**Comment by mity** [comment]
Reopening as a reminder to make the patch. I'll get to it later.
